name: 🌩 Rule-Set

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v7

    - name: 拉取规则文件
      run: python -u .github/workflows/ruleset.py

    - name: 推送规则文件
      uses: stefanzweifel/git-auto-commit-action@v7
